##
## BlakeBitcoin starter configuration file (blakebitcoin.conf).
## See config-help.md for the full 25.2 option reference.
##

#server=1
#txindex=1
#rpcuser=<user>
#rpcpassword=<password>
#rpcallowip=127.0.0.1

[main]
#port=<port>
#rpcport=<port>

[test]
#port=<port>
#rpcport=<port>

[signet]
#port=<port>
#rpcport=<port>

[regtest]
#port=<port>
#rpcport=<port>
